### ISSUE TITLE
RFC: hide .remote-snapshotter directory from getdents()

### ISSUE THREAD

**Issue by AkihiroSuda** [ktock/stargz-snapshotter#31]
Showing `.remote-snapshotter` directory in `getdents(2)` may affect `differ` implementations like https://github.com/containerd/containerd/blob/master/diff/walking/differ.go .

So maybe we should hide `.remote-snapshotter` from `getdents(2)`.

This is akin to hidden `.zfs` directories used in ZFS.

**Comment by ktock** [comment]
I agree with that. We should make `/.remote-snapshotter` read-only(or prohibit to create files in) on the *merged* rootfs as well. This is because once we create a file in `/.remote-snapshotter` overlayfs will create `.remote-snapshotter/` directory on the upper layer and the contents will be visible.

**Comment by ktock** [comment]
#48 deals with this issue.
